---
# tasks file for myvhost
# 1) 패키지 설치 - httpd
- name: 패키지 설치
  ansible.builtin.dnf:
    name: httpd
    state: present

# 2) 서비스 기동 - httpd
- name: 서비스 기동
  ansible.builtin.systemd:
    name: httpd
    state: started

# 3) 설정 파일 - /etc/httpd/conf.d/vhost.conf => notify ~ handlers
- name: 디렉토리 생성
  ansible.builtin.file:
    path: /var/www/vhosts/{{ ansible_hostname }}
    state: directory
    mode: '0755'
- name: 설정 파일
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart_httpd
- name: 파일 생성
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/vhosts/{{ ansible_hostname }}
    mode: '0644'

# 4) 방화벽 등록 - http
- name: 방화벽 등록 - http
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
