---
- name: 웹 서버 복원
  hosts: web1
  tasks:
    - name: 방화벽 제거
      ansible.posix.firewalld:
        service: http
        state: disabled
        permanent: true
        immediate: true
    - name: 웹 페이지 설정 제거
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
    - name: 웹 패키지 제거
      ansible.builtin.dnf:
        name: httpd
        state: absent
