---
- name: DB 작업
  hosts: all
  gather_facts: true
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_config_url: http://192.168.10.10
    db_config_src_path_small: "{{ db_config_url }}/my.cnf.small"
    db_config_src_path_large: "{{ db_config_url }}/my.cnf.large"
    db_config_path: /etc/my.cnf
    db_service: mariadb
  tasks:
    - name: DB 작업 수행
      ansible.builtin.include_tasks: prepare_db.yml
      when: inventory_hostname in groups['databases']
      tags:
        - dev
        - prod
      # ansible db1 -m debug -a 'var=inventory_hostname'
      # ansible db1 -m debug -a 'var=groups'
      # ansible db1 -m debug -a 'var=groups["databases"]'

  handlers:
    - name: start_db
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: started

    - name: restart_db
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: restarted
