---
- name: 0) 파일 서버 설정
  hosts: fileservers
  gather_facts: true
  tasks:
    - name: 1) 변수 포함
      ansible.builtin.include_vars: paths.yml

    - name: 2) 원격 디렉토리 생성
      ansible.builtin.file:
        path: "{{ paths.fileserver }}"
        state: directory
        mode: '0755'
      register: result

    - name: 3) result 변수 출력
      ansible.builtin.debug:
        var: result
