---
- name: 0) bashrc 파일 배포
  hosts: all
  tasks:
    - name: 1) ble.sh 설치
      ansible.builtin.copy:
        src: /home/ansible/.local/share/blesh
        dest: /home/devops/.local/share/
        owner: devops
        group: devops
        mode: 'preserve'
    - name: 2) /home/devops/.bashrc 파일 배포
      ansible.builtin.template:
        src: templates/bashrc.j2
        dest: /home/devops/.bashrc
        owner: devops
        group: devops
        mode: '0644'
