---
- name: 0) 파일 배포
  hosts: all
  vars:
    src_hosts: files/hosts
    dest_hosts: /etc/hosts
  tasks:
    - name: /etc/hosts 파일 배포
      ansible.builtin.copy:
        src: "{{ src_hosts }}"
        dest: "{{ dest_hosts }}"
        owner: root
        group: root
        mode: '0644'
