---
- name: 웹서비스 제거
  hosts: web1
  tasks:
    - name: 방화벽 서비스 제거
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled
    - name: 웹 파일 제거
      ansible.builtin.file:
        path: /var/www/html/index.php
        state: absent
    - name: 패키지 제거
      ansible.builtin.dnf:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
          - php-pdo
        state: absent
