---
- name: Task Failure Exercise
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check local time
      ansible.builtin.command: date
      register: command_result
      changed_when: false

    - name: Print local time
      ansible.builtin.debug:
        var: command_result.stdout

    - name: Block ~ Rescue ~ Always
      block:
        - name: Install package - {{ web_package }}
          ansible.builtin.yum:
            name: "{{ web_package }}"
            state: present
          failed_when: web_package == "httpd"

      rescue:
        - name: Install package - {{ db_package }}
          ansible.builtin.yum:
            name: "{{ db_package }}"
            state: present
      always:
        - name: Start service - {{ db_service }}
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started
