---
- name: 하드웨어 보고서 작성
  hosts: all
  tasks:
    - name: 파일 배포 files/hwreport.txt -> /root/hwreport.txt
      ansible.builtin.copy:
        src: files/hwreport.txt
        dest: /root/hwreport.txt
        owner: root
        group: root
        mode: '0400'
    - name: 파일 수정 - hwreport.txt의 inventoryhostname 설정
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: 'inventoryhostname'
        replace: "{{ ansible_hostname }}"
    - name: 파일 수정 - hwreport.txt의 totalmem
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: 'totalmem'
        replace: "{{ ansible_memtotal_mb }}"
    - name: 파일 수정 - hwreport.txt의 biosversion
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: 'biosversion'
        replace: "{{ ansible_bios_version }}"
    - name: 파일 수정 - hwreport.txt의 sdasize
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: 'sdasize'
        # replace: "{{ ansible_devices.sda.size }}"
        replace: "{{ ansible_facts['devices.sda.size'] }}"
    - name: 파일 모으기 hwreport.txt
      ansible.builtin.fetch:
        src: /root/hwreport.txt
        dest: ~/ansible/05_hwreport/result/hwreport-{{ inventory_hostname }}.txt
        flat: true
