---
- name: MariaDB server is installed
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    db_service: mariadb
    resources_url: http://ansible.example.com
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
    mariadb_root_password: soldesk1.
  tasks:
    - name: "{{ db_packages }} packages are installed"
      ansible.builtin.yum:
        name: "{{ db_packages }}"
        state: present
      notify:
        - set db password

    - name: Make sure the database service is running
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: started
        enabled: true
    - name: Write root login credentials
      ansible.builtin.copy:
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'
        content: |
          [client]
          user=root
          password={{ mariadb_root_password }}
          socket=/var/lib/mysql/mysql.sock

    - name: The {{ config_file_dst }} file has been installed
      ansible.builtin.get_url:
        url: "{{ config_file_url }}"
        dest: "{{ config_file_dst }}"
        owner: mysql
        group: mysql
        force: true
        mode: '0644'
      notify:
        - restart db service

  handlers:
    - name: Restart db service
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: restarted

    - name: Set db password
      community.mysql.mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        priv: '*.*:ALL'
        state: present
