---
- name: DB 서버 복원
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
    config_file_dst: /etc/my.cnf
  tasks:
    - name: 파일 제거
      ansible.builtin.file:
        path: "{{ config_file_dst }}"
        state: absent
    - name: 파일 제거
      ansible.builtin.file:
        dest: /root/.my.cnf
        state: absent

    - name: 패키지 제거
      ansible.builtin.yum:
        name: "{{ db_packages }}"
        state: absent
